#!/usr/bin/env node
// Build pipeline: design-system/tokens.json (authoring) →
//   tokens/canonical.json + canonical.schema.json (validated)
//   → tokens/dtcg.json + tokens/figma-map.json (Figma projection).
//
// Pure Node, no runtime deps. Run via `npm run tokens:build`.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { project as figmaProject } from "../lib/interpreters/figma.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(ROOT, "design-system/tokens.json");
const OUT_DIR = join(ROOT, "tokens");

const PROVENANCE_KEYS = new Set([
  "role",
  "evidence",
  "applies_to",
  "note",
  "extrapolated",
  "disambiguation",
  "name",
  "description",
  "supersedes",
  "color_default",
  "color_description",
  "ascii_fallback",
]);

// ---------- Authoring → Canonical ----------

const authoring = JSON.parse(readFileSync(SRC, "utf-8"));

const canonical = {
  $meta: {
    ...authoring.$meta,
    generated: new Date().toISOString().slice(0, 10),
    source: "design-system/tokens.json",
    note: "Generated by scripts/build-tokens.mjs. Do not hand-edit. Edit the authoring source instead.",
  },
  color: normalizeColor(authoring.color),
  typography: normalizeTypography(authoring.typography),
  spacing: normalizeSpacing(authoring.spacing),
  glyph: normalizeGlyphs(authoring.glyph),
  banner: normalizeBanner(authoring.banner),
  link: normalizeLink(authoring.link),
  machine_readable: normalizeMachineReadable(authoring.machine_readable),
};

function normalizeColor(node) {
  const out = {};
  if (node.$description) out.$description = node.$description;
  for (const groupKey of Object.keys(node)) {
    if (groupKey.startsWith("$")) continue;
    const group = node[groupKey];

    // The `fallback` group is descriptive prose, no leaf color values.
    // Preserve verbatim so downstream readers (LLMs included) keep the context.
    if (groupKey === "fallback") {
      out.fallback = { ...group, $kind: "descriptive" };
      continue;
    }

    const groupOut = {};
    if (group.$description) groupOut.$description = group.$description;
    for (const tokenKey of Object.keys(group)) {
      if (tokenKey.startsWith("$")) continue;
      const t = group[tokenKey];
      groupOut[tokenKey] = liftColor(t);
    }
    out[groupKey] = groupOut;
  }
  return out;
}

function liftColor(t) {
  const result = {
    $type: "color",
    $value: t.value,
  };
  if (t.name) result.name = t.name;
  for (const k of ["role", "applies_to", "evidence"]) {
    if (k in t) result[k] = t[k];
  }
  return result;
}

function normalizeTypography(node) {
  const out = {};
  if (node.$description) out.$description = node.$description;
  for (const key of Object.keys(node)) {
    if (key.startsWith("$")) continue;
    const t = node[key];

    // monospace is purely descriptive (font stack for mockups).
    if (key === "monospace") {
      out.monospace = {
        $type: "font_stack",
        $value: t.stack_for_mockups || [],
        $description: t.$description,
      };
      continue;
    }

    out[key] = {
      $type: "typography",
      $value: {
        weight: t.weight,
        case: t.case,
        letterSpacing: t.letter_spacing,
        color: t.color, // dot-notation reference, e.g. "color.text.primary"
        underline: t.underline,
      },
      role: t.role,
      applies_to: t.applies_to,
      supersedes: t.supersedes,
      evidence: t.evidence,
    };
    // Strip undefined values for cleanliness.
    pruneUndefined(out[key].$value);
    pruneUndefined(out[key]);
  }
  return out;
}

function normalizeSpacing(node) {
  const out = {};
  if (node.$description) out.$description = node.$description;

  for (const groupKey of Object.keys(node)) {
    if (groupKey.startsWith("$")) continue;
    const group = node[groupKey];
    const groupOut = {};
    for (const tokenKey of Object.keys(group)) {
      if (tokenKey.startsWith("$")) continue;
      const t = group[tokenKey];
      groupOut[tokenKey] = liftSpacing(t, groupKey);
    }
    out[groupKey] = groupOut;
  }
  return out;
}

function liftSpacing(t, groupKey) {
  const parsed = parseSpacingValue(t.value);
  const context = groupKey === "indent" ? "indent" : "section_gap";

  // Compound values become an object describing each axis position.
  let $value;
  if (parsed.kind === "compound") {
    $value = {
      above: { count: parsed.above.count, unit: parsed.above.unit },
      below: { count: parsed.below.count, unit: parsed.below.unit },
      axis: "vertical",
      context,
    };
  } else {
    $value = {
      count: parsed.count,
      unit: parsed.unit,
      axis: parsed.axis,
      context,
    };
  }

  const result = {
    $type: "terminal.spacing",
    $value,
    $source: t.value, // preserve the human-authored phrase verbatim
  };
  for (const k of ["role", "evidence", "note"]) {
    if (k in t) result[k] = t[k];
  }
  return result;
}

function parseSpacingValue(raw) {
  const s = String(raw).trim();

  // Compound: "1 blank line above, 0 below" or "0 above, 1 blank line below".
  if (/above/.test(s) && /below/.test(s)) {
    const aboveMatch = s.match(/(\d+)\s*(blank lines?|spaces?)?\s+above/);
    const belowMatch = s.match(/(\d+)\s*(blank lines?|spaces?)?\s+below/);
    return {
      kind: "compound",
      above: parsePart(aboveMatch),
      below: parsePart(belowMatch),
    };
  }

  // "N spaces" → horizontal.
  let m = s.match(/^(\d+)\s+spaces?$/);
  if (m) {
    return { kind: "simple", count: Number(m[1]), unit: "space", axis: "horizontal" };
  }

  // "N blank line(s)" → vertical.
  m = s.match(/^(\d+)\s+blank\s+lines?$/);
  if (m) {
    return { kind: "simple", count: Number(m[1]), unit: "blank_line", axis: "vertical" };
  }

  // Fallback: treat as opaque. Should not happen with the current authoring source.
  return { kind: "simple", count: 0, unit: "unknown", axis: "unknown", raw: s };
}

function parsePart(match) {
  if (!match) return { count: 0, unit: "blank_line" };
  const count = Number(match[1]);
  const unitText = (match[2] || "blank line").toLowerCase();
  const unit = unitText.includes("space") ? "space" : "blank_line";
  return { count, unit };
}

function normalizeGlyphs(node) {
  const out = {};
  if (node.$description) out.$description = node.$description;
  for (const key of Object.keys(node)) {
    if (key.startsWith("$")) continue;
    const g = node[key];
    out[key] = {
      $type: "terminal.glyph",
      $value: {
        char: g.char,
        asciiFallback: g.ascii_fallback,
        role: key,
        color: extractColorReference(g.color_default),
        validColors: g.valid_colors,
      },
      color_description: g.color_default,
      role: g.role,
      evidence: g.evidence,
    };
    if (g.disambiguation) out[key].disambiguation = g.disambiguation;
    if (g.extrapolated) out[key].extrapolated = g.extrapolated;
    pruneUndefined(out[key].$value);
    pruneUndefined(out[key]);
  }
  return out;
}

function extractColorReference(text) {
  if (!text) return undefined;
  // Pull the first dot-notation color reference out of free prose.
  const m = String(text).match(/color\.[a-z_]+\.[a-z_]+/i);
  return m ? m[0] : undefined;
}

function normalizeBanner(node) {
  const out = {};
  if (node.$description) out.$description = node.$description;

  if (node.start) {
    out.start = {
      $type: "terminal.banner.start",
      $value: {
        rich: node.start.rich,
        asciiFallback: node.start.ascii_fallback,
        shape: node.start.shape,
      },
      evidence: node.start.evidence,
    };
  }
  if (node.close) {
    const variants = {};
    for (const v of Object.keys(node.close.variants || {})) {
      const vv = node.close.variants[v];
      variants[v] = {
        $type: "terminal.banner.close",
        $value: {
          phrase: vv.phrase,
          color: vv.color, // dot-notation reference
        },
        evidence: vv.evidence,
      };
    }
    out.close = {
      $shape: node.close.shape,
      weight: node.close.weight,
      leadingBlankLine: node.close.leading_blank_line,
      noGlyph: node.close.no_glyph,
      variants,
    };
  }
  return out;
}

function normalizeLink(node) {
  return {
    $type: "link.policy",
    $value: {
      transport: node.transport,
      color: node.color,
      underlinePolicy: node.underline_policy,
      linkableTargets: node.linkable_targets,
      fallback: node.fallback,
    },
    $description: node.$description,
    evidence: node.evidence,
  };
}

function normalizeMachineReadable(node) {
  return {
    $type: "render.policy",
    $value: {
      color: node.color,
      glyph: node.glyph,
      weight: node.weight,
      errorShape: node.error_shape,
    },
    $description: node.$description,
    out_of_scope: node.out_of_scope,
    evidence: node.evidence,
  };
}

function pruneUndefined(obj) {
  for (const k of Object.keys(obj)) {
    if (obj[k] === undefined) delete obj[k];
  }
}

// ---------- Schema ----------

const schema = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "https://construct.moderne.io/tokens/canonical.schema.json",
  title: "Construct canonical tokens",
  description:
    "Canonical, normalized projection of design-system/tokens.json. Preserves all semantic provenance (role, evidence, applies_to, etc.). Consumed by interpreters and by the Next.js documentation surface.",
  type: "object",
  required: ["$meta", "color", "typography", "spacing", "glyph", "banner", "link", "machine_readable"],
  properties: {
    $meta: {
      type: "object",
      required: ["name", "version", "phase"],
      additionalProperties: true,
    },
    color: {
      type: "object",
      patternProperties: {
        "^(?!\\$)[a-z_]+$": {
          type: "object",
          patternProperties: {
            "^(?!\\$)[a-z_]+$": {
              oneOf: [
                {
                  type: "object",
                  required: ["$type", "$value"],
                  properties: {
                    $type: { const: "color" },
                    $value: { type: "string", pattern: "^#[0-9a-fA-F]{6}$" },
                  },
                  additionalProperties: true,
                },
                {
                  // descriptive subgroup like color.fallback
                  type: "object",
                  required: ["$kind"],
                  properties: { $kind: { const: "descriptive" } },
                  additionalProperties: true,
                },
                { type: "string" },
              ],
            },
          },
          additionalProperties: true,
        },
      },
      additionalProperties: true,
    },
    typography: { type: "object", additionalProperties: true },
    spacing: {
      type: "object",
      patternProperties: {
        "^(?!\\$)[a-z_]+$": {
          type: "object",
          patternProperties: {
            "^(?!\\$)[a-z_]+$": {
              type: "object",
              required: ["$type", "$value"],
              properties: {
                $type: { const: "terminal.spacing" },
                $value: {
                  oneOf: [
                    {
                      type: "object",
                      required: ["count", "unit", "axis", "context"],
                      properties: {
                        count: { type: "integer", minimum: 0 },
                        unit: { enum: ["space", "blank_line", "unknown"] },
                        axis: { enum: ["horizontal", "vertical", "unknown"] },
                        context: { type: "string" },
                      },
                      additionalProperties: false,
                    },
                    {
                      type: "object",
                      required: ["above", "below", "axis", "context"],
                      properties: {
                        above: {
                          type: "object",
                          required: ["count", "unit"],
                          properties: {
                            count: { type: "integer", minimum: 0 },
                            unit: { enum: ["space", "blank_line"] },
                          },
                          additionalProperties: false,
                        },
                        below: {
                          type: "object",
                          required: ["count", "unit"],
                          properties: {
                            count: { type: "integer", minimum: 0 },
                            unit: { enum: ["space", "blank_line"] },
                          },
                          additionalProperties: false,
                        },
                        axis: { enum: ["vertical"] },
                        context: { type: "string" },
                      },
                      additionalProperties: false,
                    },
                  ],
                },
              },
              additionalProperties: true,
            },
          },
          additionalProperties: true,
        },
      },
      additionalProperties: true,
    },
    glyph: {
      type: "object",
      patternProperties: {
        "^(?!\\$)[a-z_]+$": {
          type: "object",
          required: ["$type", "$value"],
          properties: {
            $type: { const: "terminal.glyph" },
            $value: {
              type: "object",
              required: ["char", "asciiFallback", "role", "validColors"],
              properties: {
                char: { type: "string", minLength: 1 },
                asciiFallback: { type: "string", minLength: 1 },
                role: { type: "string" },
                color: { type: "string" },
                validColors: {
                  type: "array",
                  items: { type: "string", pattern: "^(text|semantic|background)\\.[a-z_]+$" },
                },
              },
              additionalProperties: false,
            },
          },
          additionalProperties: true,
        },
      },
      additionalProperties: true,
    },
    banner: { type: "object", additionalProperties: true },
    link: { type: "object", additionalProperties: true },
    machine_readable: { type: "object", additionalProperties: true },
  },
  additionalProperties: true,
};

// ---------- Hand-rolled validator (no runtime deps) ----------
// Implements the subset of JSON Schema used above: type, required, properties,
// patternProperties, additionalProperties, oneOf, const, enum, minLength,
// minimum, pattern, items.

function validate(data, schema, path = "$") {
  const errors = [];

  if (schema.const !== undefined) {
    if (data !== schema.const) errors.push(`${path}: expected const ${JSON.stringify(schema.const)}, got ${JSON.stringify(data)}`);
  }
  if (schema.enum) {
    if (!schema.enum.includes(data)) errors.push(`${path}: expected one of ${schema.enum.join(", ")}, got ${JSON.stringify(data)}`);
  }
  if (schema.type) {
    const ok = checkType(data, schema.type);
    if (!ok) errors.push(`${path}: expected type ${schema.type}, got ${typeofJson(data)}`);
  }
  if (schema.minLength !== undefined && typeof data === "string" && data.length < schema.minLength) {
    errors.push(`${path}: minLength ${schema.minLength}, got ${data.length}`);
  }
  if (schema.minimum !== undefined && typeof data === "number" && data < schema.minimum) {
    errors.push(`${path}: minimum ${schema.minimum}, got ${data}`);
  }
  if (schema.pattern && typeof data === "string" && !new RegExp(schema.pattern).test(data)) {
    errors.push(`${path}: does not match pattern ${schema.pattern}`);
  }
  if (schema.oneOf) {
    const matches = schema.oneOf.filter((s) => validate(data, s, path).length === 0);
    if (matches.length !== 1) errors.push(`${path}: oneOf matched ${matches.length} schemas (expected 1)`);
  }
  if (schema.required && data && typeof data === "object") {
    for (const r of schema.required) {
      if (!(r in data)) errors.push(`${path}: missing required key '${r}'`);
    }
  }
  if (schema.properties && data && typeof data === "object" && !Array.isArray(data)) {
    for (const k of Object.keys(schema.properties)) {
      if (k in data) errors.push(...validate(data[k], schema.properties[k], `${path}.${k}`));
    }
  }
  if (schema.patternProperties && data && typeof data === "object" && !Array.isArray(data)) {
    for (const pat of Object.keys(schema.patternProperties)) {
      const re = new RegExp(pat);
      for (const k of Object.keys(data)) {
        if (re.test(k)) errors.push(...validate(data[k], schema.patternProperties[pat], `${path}.${k}`));
      }
    }
  }
  if (schema.additionalProperties === false && data && typeof data === "object" && !Array.isArray(data)) {
    const allowed = new Set([
      ...(schema.properties ? Object.keys(schema.properties) : []),
    ]);
    const patterns = (schema.patternProperties ? Object.keys(schema.patternProperties) : []).map((p) => new RegExp(p));
    for (const k of Object.keys(data)) {
      if (allowed.has(k)) continue;
      if (patterns.some((re) => re.test(k))) continue;
      errors.push(`${path}: unexpected property '${k}'`);
    }
  }
  if (schema.items && Array.isArray(data)) {
    data.forEach((item, i) => errors.push(...validate(item, schema.items, `${path}[${i}]`)));
  }
  return errors;
}

function checkType(data, type) {
  switch (type) {
    case "object":
      return data !== null && typeof data === "object" && !Array.isArray(data);
    case "array":
      return Array.isArray(data);
    case "string":
      return typeof data === "string";
    case "integer":
      return Number.isInteger(data);
    case "number":
      return typeof data === "number";
    case "boolean":
      return typeof data === "boolean";
    case "null":
      return data === null;
    default:
      return true;
  }
}

function typeofJson(d) {
  if (d === null) return "null";
  if (Array.isArray(d)) return "array";
  return typeof d;
}

// ---------- Run ----------

mkdirSync(OUT_DIR, { recursive: true });

const errors = validate(canonical, schema);
if (errors.length) {
  console.error("✗ canonical.json failed schema validation:");
  for (const e of errors) console.error("  -", e);
  process.exit(1);
}

writeFileSync(join(OUT_DIR, "canonical.json"), JSON.stringify(canonical, null, 2) + "\n");
writeFileSync(join(OUT_DIR, "canonical.schema.json"), JSON.stringify(schema, null, 2) + "\n");
console.log("✓ wrote tokens/canonical.json");
console.log("✓ wrote tokens/canonical.schema.json");

const { dtcg, figmaMap } = figmaProject(canonical);
writeFileSync(join(OUT_DIR, "dtcg.json"), JSON.stringify(dtcg, null, 2) + "\n");
writeFileSync(join(OUT_DIR, "figma-map.json"), JSON.stringify(figmaMap, null, 2) + "\n");
console.log("✓ wrote tokens/dtcg.json");
console.log("✓ wrote tokens/figma-map.json");
